### PR TITLE
Update facter::fact to default 'facts_dir' to 'facter::facts_d_dir'.

### PR DESCRIPTION
**Pull request by fatmcgav**
Add test case to exercise and fix failing test due to pre_condition.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Thanks for the contribution @fatmcgav 

We're currently working on a new version of the module that drops support for Puppet 3 in the `puppet5` branch. Perhaps you would like to target your change against that?

https://github.com/ghoneycutt/puppet-module-facter/tree/puppet5

https://github.com/ghoneycutt/puppet-module-facter/issues/57

**Comment by fatmcgav** [comment]
@ghoneycutt That's probably sensible... I'll update PR now :)

**Comment by fatmcgav** [comment]
Hmm, i'm not sure why Github has picked up 3 other commits on that forced update... :s 

But same change applied to puppet5 branch :)

**Comment by fatmcgav** [comment]
Superseded by #62

**Pull request closed without merging**
