### PR TITLE
add $purge_facts_d boolean to delete unmanaged txt files from facts.d…

### PR DESCRIPTION
**Pull request by janvonde**
… directory

### CODE REVIEW

**Comment by ghoneycutt** [comment]
Suggest doing this separate and getting it merged then moving on to #33 so we can make incremental progress

**Comment by janvonde** [comment]
check, once this is done I will update my other pull request.

**Comment by janvonde** [comment]
I followed your instructions from #33 to install bundle and run the tests. This gives an error that I do not understand. The failure is:
```
Failures:

  1) facter should compile into a catalogue without dependency cycles
     Failure/Error: it { should compile.with_all_deps }
       error during compilation: Could not autoload puppet/type/package: Could not autoload puppet/provider/package/pkgdmg: cannot load such file -- plist on node 9000100750.fritz.box
     # ./spec/classes/init_spec.rb:4:in `block (2 levels) in <top (required)>'

Finished in 1.49 seconds (files took 0.51238 seconds to load)
69 examples, 1 failure

Failed examples:

rspec ./spec/classes/init_spec.rb:4 # facter should compile into a catalogue without dependency cycles
```

You can find the full output at http://0bin.net/paste/BSLAcQQtSOSfngpy#lg+WDCirPti0NLFRhyRtxOmPWjFTkOBCXearhrRNpSA

Can you give me a hint on how to understand and fix the error?

**Comment by ghoneycutt** [comment]
Not quite sure.

**Comment by ghoneycutt** [comment]
Hi @janvonde 

I'm modifying your work in PR #37

Thanks a ton!

**Pull request closed without merging**
