### PR TITLE
Prep v4

### PR DESCRIPTION
**Pull request by ghoneycutt**
TODO

- [x] documentation
- [x] double check type validation
- [x] rebase/squash commits
- [x] travis working
- [x] appveyor working
- [x] add support for json or yaml facts. needed to support values beyond strings.
  - [x] rename `facter::yaml` to `facter::structured_data_fact`
- [x] fix `Untouched resources` in spec tests
- [x] go through existing PR's and either merge into here or close
  - [ ] switch to using concat instead of file_line so that entries can be purged.

### CODE REVIEW

**Comment by ghoneycutt** [comment]
@nmaludy Could you please have a look at this? Seems the mkdir is failing on windows. Could you test this branch on a windows system? Then we can see if this is just related to AppVeyor or not.

**Comment by ghoneycutt** [comment]
https://ci.appveyor.com/project/ghoneycutt/puppet-module-facter/build/job/xsjsi0qanaeh7dde#L1117

**Comment by nmaludy** [comment]
@ghoneycutt i'm guessing this is OK because of this ```Debug: /Stage[main]/Facter/Exec[mkdir_p-C:\ProgramData\PuppetLabs\facter\facts.d]: 'cmd /c mkdir C:\ProgramData\PuppetLabs\facter\facts.d' won't be executed because of failed check 'creates'```

Looks like the directory already exists, so it's not being created by this resource because of the `creates` guard parameter: https://github.com/ghoneycutt/puppet-module-facter/blob/master/manifests/init.pp#L36

**Comment by nmaludy** [comment]
Looking further, do warnings in the `idempotent apply` test cause failures? https://ci.appveyor.com/project/ghoneycutt/puppet-module-facter/build/job/xsjsi0qanaeh7dde#L1132

```
Warning: Facter: Fact file C:\ProgramData/PuppetLabs/facter/facts.d/facts.txt was parsed but returned an empty data set
Warning: Facter: Fact file C:\ProgramData/PuppetLabs/facter/facts.d/facts.txt was parsed but returned an empty data set
```

If so, it looks like we're defining the file here: https://github.com/ghoneycutt/puppet-module-facter/blob/master/manifests/init.pp#L68-L74

If no `facter::fact` are defined, then that file is empty and those warnings are emitted.

**Comment by ghoneycutt** [comment]
This content match does not seem to be implemented correctly in windows

```
    context 'and should contain facts' do
      describe file(test_facts_file) do
        its(:content) { should match %r{test_fact=test_value} }
      end
```

as it results in

```
 3) facter class with specifying facts_hash and should contain facts File "C:\ProgramData\PuppetLabs\facter\facts.d\test.txt" content is expected to match /test_fact=test_value/
     Failure/Error: its(:content) { should match %r{test_fact=test_value} }
       expected "" to match /test_fact=test_value/
       Diff:
       @@ -1,2 +1,2 @@
       -/test_fact=test_value/
       +""
       Get-Content("C:\ProgramData\PuppetLabs\facter\facts.d\test.txt") | Write-Host
       #< CLIXML
<Objs Version="1.1.0.1" xmlns="http://schemas.microsoft.com/powershell/2004/04"><Obj S="progress" RefId="0"><TN RefId="0"><T>System.Management.Automation.PSCustomObject</T><T>System.Object</T></TN><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj><Obj S="progress" RefId="1"><TNRef RefId="0" /><MS><I64 N="SourceId">1</I64><PR N="Record"><AV>Preparing modules for first use.</AV><AI>0</AI><Nil /><PI>-1</PI><PC>-1</PC><T>Completed</T><SR>-1</SR><SD> </SD></PR></MS></Obj></Objs>
```

Do you know of another way using the command line to test? Might be easier to use `file` for posix and `command` for windows.

**Comment by nmaludy** [comment]
got elevated commands to work using `psexec.exe`:
```
PS C:\Users\appveyor> PsExec.exe -s 'C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat' --versionPsExec v2.11 - Execute processes remotely
Copyright (C) 2001-2014 Mark Russinovich
Sysinternals - www.sysinternals.com5.5.19
C:\Program Files\Puppet Labs\Puppet\bin\puppet.bat exited on APPVYR-WIN with error code 0.
```

**Comment by ghoneycutt** [comment]
That worked for windows 2015 and failed for 2017 and 2019 because you have to accept a eula to use psexec. Adding that step to appveyor.

**Comment by ghoneycutt** [comment]
100% coverage on resources

**Comment by ghoneycutt** [comment]
rebasing seems to confuse appveyor as it does not run. When manually triggered, it works.

**Comment by nmaludy** [comment]
that's awesome! well done!

**Comment by jcpunk** [comment]
I'd love to see this work completed and published for puppet7

**Comment by ghoneycutt** [comment]
@jcpunk Released! https://forge.puppet.com/modules/ghoneycutt/facter/4.0.0

**Comment by jcpunk** [comment]
:)

**Pull request merged**
